# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballerine_app', '0002_homeimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeImages',
            new_name='HomeImage',
        ),
    ]
