# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballerine_app', '0005_auto_20161108_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
