# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballerine_app', '0006_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
